<?php

/**
 * @file bare_pages.module
 * This is a fork & "fragmentation" of the 'modalframe' contrib module.
 * It provides a generic way to render only page content (e.g. without blocks,
 * regions, admin menu, etc.). Its main purpose is to facilitate the use of iframes,
 * often inside modal popups. Planned support for Colorbox and Bootstrap - for jquery UI Dialog, prefer the original modalframe module.
 */

$path = drupal_get_path('module', 'bare_pages');
include $path . '/includes/theme.inc';
include $path . '/includes/form.inc';
include $path . '/includes/context.inc';
include $path . '/includes/modal.inc';
